//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportFox
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftList
    {
        public string Soft_Name { get; set; }
        public Nullable<int> List_ID { get; set; }
    
        public virtual List_ID List_ID1 { get; set; }
    }
}
