//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportFox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public int ID { get; set; }
        public string Hardware_ID { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Folder { get; set; }
        public System.DateTime Installdate { get; set; }
        public System.DateTime Lastdate { get; set; }
    
        public virtual Hardware Hardware { get; set; }
    }
}
